# Indexing Pandas

In [1]:
# Cambio y filtracion de indexacion y multi indexacion 

import pandas as pd

In [4]:
df = pd.read_csv("../Data_Science_Alex/world_population.csv")
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [11]:
# Index: cambiar de nombre la columna Country al inicio del dataframe
df = pd.read_csv("../Data_Science_Alex/world_population.csv", index_col = 'Country')
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [13]:
# Como invertir el datraframe
df.reset_index(inplace=True)
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [15]:
df.set_index('Country', inplace = True) #Inplace = True, permite guardar el comando de nombre de la columna Country 
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [23]:
# Forma comun de encontrar data en el dataframe

#loc 

df.loc['Albania'] # permite la localizacion de la columna del pais seleccionado, para ver todos sus datos

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [25]:
df.iloc[1] #iloc, permite seleccionar el numero de fila

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [27]:
df.iloc[4]

Rank                                        203
CCA3                                        AND
Capital                        Andorra la Vella
Continent                                Europe
2022 Population                         79824.0
2020 Population                         77700.0
2015 Population                         71746.0
2010 Population                         71519.0
2000 Population                         66097.0
1990 Population                         53569.0
1980 Population                         35611.0
1970 Population                         19860.0
Area (km²)                                468.0
Density (per km²)                      170.5641
Growth Rate                                1.01
World Population Percentage                 0.0
Name: Andorra, dtype: object

In [29]:
df.loc['Andorra']

Rank                                        203
CCA3                                        AND
Capital                        Andorra la Vella
Continent                                Europe
2022 Population                         79824.0
2020 Population                         77700.0
2015 Population                         71746.0
2010 Population                         71519.0
2000 Population                         66097.0
1990 Population                         53569.0
1980 Population                         35611.0
1970 Population                         19860.0
Area (km²)                                468.0
Density (per km²)                      170.5641
Growth Rate                                1.01
World Population Percentage                 0.0
Name: Andorra, dtype: object

In [33]:
df.reset_index(inplace = True)
df

,index,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [53]:
df.reset_index(inplace = True)

In [55]:
# Multi-indexing
# Se tiene dos indexes obtenidos, Continent y Country
df.set_index(['Continent', 'Country'], inplace = True)
df

                             index  Rank CCA3           Capital  \
Continent Country
Asia      Afghanistan            0    36  AFG             Kabul
Europe    Albania                1   138  ALB            Tirana
Africa    Algeria                2    34  DZA           Algiers
Oceania   American Samoa         3   213  ASM         Pago Pago
Europe    Andorra                4   203  AND  Andorra la Vella
...                            ...   ...  ...               ...
Oceania   Wallis and Futuna    229   226  WLF          Mata-Utu
Africa    Western Sahara       230   172  ESH          El Aaiún
Asia      Yemen                231    46  YEM             Sanaa
Africa    Zambia               232    63  ZMB            Lusaka
          Zimbabwe             233    74  ZWE            Harare

                             2022 Population  2020 Population  \
Continent Country
Asia      Afghanistan             41128771.0       38972230.0
Europe    Albania                  2842321.0        2866849.0
Africa    Algeria                 44903225.0       43451666.0
Oceania   American Samoa             44273.0          46189.0
Europe    Andorra                    79824.0          77700.0
...                                      ...              ...
Oceania   Wallis and Futuna          11572.0          11655.0
Africa    Western Sahara            575986.0         556048.0
Asia      Yemen                   33696614.0       32284046.0
Africa    Zambia                  20017675.0       18927715.0
          Zimbabwe                16320537.0       15669666.0

                             2015 Population  2010 Population  \
Continent Country
Asia      Afghanistan             33753499.0       28189672.0
Europe    Albania                  2882481.0        2913399.0
Africa    Algeria                 39543154.0       35856344.0
Oceania   American Samoa             51368.0          54849.0
Europe    Andorra                    71746.0          71519.0
...                                      ...              ...
Oceania   Wallis and Futuna          12182.0          13142.0
Africa    Western Sahara            491824.0         413296.0
Asia      Yemen                   28516545.0       24743946.0
Africa    Zambia                         NaN       13792086.0
          Zimbabwe                14154937.0       12839771.0

                             2000 Population  1990 Population  \
Continent Country
Asia      Afghanistan             19542982.0       10694796.0
Europe    Albania                  3182021.0        3295066.0
Africa    Algeria                 30774621.0       25518074.0
Oceania   American Samoa             58230.0          47818.0
Europe    Andorra                    66097.0          53569.0
...                                      ...              ...
Oceania   Wallis and Futuna          14723.0          13454.0
Africa    Western Sahara            270375.0         178529.0
Asia      Yemen                   18628700.0       13375121.0
Africa    Zambia                   9891136.0        7686401.0
          Zimbabwe                11834676.0       10113893.0

                             1980 Population  1970 Population  Area (km²)  \
Continent Country
Asia      Afghanistan             12486631.0       10752971.0    652230.0
Europe    Albania                  2941651.0        2324731.0     28748.0
Africa    Algeria                 18739378.0       13795915.0   2381741.0
Oceania   American Samoa             32886.0          27075.0       199.0
Europe    Andorra                    35611.0          19860.0       468.0
...                                      ...              ...         ...
Oceania   Wallis and Futuna          11315.0           9377.0       142.0
Africa    Western Sahara            116775.0          76371.0    266000.0
Asia      Yemen                    9204938.0        6843607.0    527968.0
Africa    Zambia                   5720438.0        4281671.0    752612.0
          Zimbabwe                 7049926.0        5202918.0    390757.0

                             Density (per km²)  Growth Rate  \
Continent Country
Asia      Afghanistan                  63.0587       1.0257
Europe    Albania                      98.8702       0.9957
Africa    Algeria                      18.8531       1.0164
Oceania   American Samoa              222.4774       0.9831
Europe    Andorra                     170.5641       1.0100
...                                        ...          ...
Oceania   Wallis and Futuna            81.4930       0.9953
Africa    Western Sahara                2.1654       1.0184
Asia      Yemen                        63.8232       1.0217
Africa    Zambia                       26.5976       1.0280
          Zimbabwe                     41.7665       1.0204

                             World Population Percentage
Continent Country
Asia      Afghanistan                               0.52
Europe    Albania                                   0.04
Africa    Algeria                                   0.56
Oceania   American Samoa                            0.00
Europe    Andorra                                   0.00
...                                                  ...
Oceania   Wallis and Futuna                         0.00
Africa    Western Sahara                            0.01
Asia      Yemen                                     0.42
Africa    Zambia                                    0.25
          Zimbabwe                                  0.20

[234 rows x 16 columns]

In [57]:
# Mejorar estos valores de la tabla anterior, ordenando (sort) la tabla
df.sort_index()

                            index  Rank CCA3      Capital  2022 Population  \
Continent     Country
Africa        Algeria           2    34  DZA      Algiers       44903225.0
              Angola            5    42  AGO       Luanda       35588987.0
              Benin            21    77  BEN   Porto-Novo       13352864.0
              Botswana         26   144  BWA     Gaborone        2630296.0
              Burkina Faso     31    58  BFA  Ouagadougou       22673762.0
...                           ...   ...  ...          ...              ...
South America Paraguay        161   109  PRY     Asunción        6780744.0
              Peru            162    44  PER         Lima       34049588.0
              Suriname        199   170  SUR   Paramaribo         618040.0
              Uruguay         223   133  URY   Montevideo        3422794.0
              Venezuela       227    51  VEN      Caracas       28301696.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
Africa        Algeria            43451666.0       39543154.0       35856344.0
              Angola             33428485.0       28127721.0       23364185.0
              Benin              12643123.0       10932783.0        9445710.0
              Botswana            2546402.0        2305171.0        2091664.0
              Burkina Faso       21522626.0       18718019.0       16116845.0
...                                     ...              ...              ...
South America Paraguay            6618695.0        6177950.0        5768613.0
              Peru               33304756.0       30711863.0       29229572.0
              Suriname             607065.0         575475.0         546080.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Venezuela          28490453.0       30529716.0       28715022.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
Africa        Algeria            30774621.0       25518074.0       18739378.0
              Angola             16394062.0       11828638.0        8330047.0
              Benin               6998023.0        5133419.0        3833939.0
              Botswana            1726985.0        1341474.0         938578.0
              Burkina Faso       11882888.0        9131361.0        6932967.0
...                                     ...              ...              ...
South America Paraguay            5123819.0        4059195.0        3078912.0
              Peru               26654439.0       22109099.0       17492406.0
              Suriname             478998.0         412756.0         375112.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Venezuela                 NaN       19750579.0       15210443.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
Africa        Algeria            13795915.0   2381741.0            18.8531
              Angola              6029700.0   1246700.0            28.5466
              Benin               3023443.0    112622.0           118.5635
              Botswana             592244.0    582000.0             4.5194
              Burkina Faso        5611666.0    272967.0            83.0641
...                                     ...         ...                ...
South America Paraguay            2408787.0    406752.0            16.6705
              Peru               13562371.0   1285216.0            26.4933
              Suriname             379918.0    163820.0             3.7727
              Uruguay             2790265.0    181034.0            18.9069
              Venezuela          11355475.0         NaN            30.8820

                            Growth Rate  World Population Percentage
Continent     Country
Africa        Algeria            1.0164                         0.56
              Angola             1.0315                         0.45
              Benin              1.0274                         0.17
              Botswana           1.0162                         0.03
              Burkina Faso       1.0259                         0.28
...                                 ...                          ...
South America Paraguay           1.0115                         0.09
              Peru               1.0099                         0.43
              Suriname           1.0082                         0.01
              Uruguay            0.9990                         0.04
              Venezuela          1.0036                         0.35

[234 rows x 16 columns]

In [67]:
df.sort_index(ascending =False) # se ordena de forma alfabetica o no

                            index  Rank CCA3      Capital  2022 Population  \
Continent     Country
South America Venezuela       227    51  VEN      Caracas       28301696.0
              Uruguay         223   133  URY   Montevideo        3422794.0
              Suriname        199   170  SUR   Paramaribo         618040.0
              Peru            162    44  PER         Lima       34049588.0
              Paraguay        161   109  PRY     Asunción        6780744.0
...                           ...   ...  ...          ...              ...
Africa        Burkina Faso     31    58  BFA  Ouagadougou       22673762.0
              Botswana         26   144  BWA     Gaborone        2630296.0
              Benin            21    77  BEN   Porto-Novo       13352864.0
              Angola            5    42  AGO       Luanda       35588987.0
              Algeria           2    34  DZA      Algiers       44903225.0

                            2020 Population  2015 Population  2010 Population  \
Continent     Country
South America Venezuela          28490453.0       30529716.0       28715022.0
              Uruguay             3429086.0        3402818.0        3352651.0
              Suriname             607065.0         575475.0         546080.0
              Peru               33304756.0       30711863.0       29229572.0
              Paraguay            6618695.0        6177950.0        5768613.0
...                                     ...              ...              ...
Africa        Burkina Faso       21522626.0       18718019.0       16116845.0
              Botswana            2546402.0        2305171.0        2091664.0
              Benin              12643123.0       10932783.0        9445710.0
              Angola             33428485.0       28127721.0       23364185.0
              Algeria            43451666.0       39543154.0       35856344.0

                            2000 Population  1990 Population  1980 Population  \
Continent     Country
South America Venezuela                 NaN       19750579.0       15210443.0
              Uruguay             3292224.0        3117012.0        2953750.0
              Suriname             478998.0         412756.0         375112.0
              Peru               26654439.0       22109099.0       17492406.0
              Paraguay            5123819.0        4059195.0        3078912.0
...                                     ...              ...              ...
Africa        Burkina Faso       11882888.0        9131361.0        6932967.0
              Botswana            1726985.0        1341474.0         938578.0
              Benin               6998023.0        5133419.0        3833939.0
              Angola             16394062.0       11828638.0        8330047.0
              Algeria            30774621.0       25518074.0       18739378.0

                            1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
South America Venezuela          11355475.0         NaN            30.8820
              Uruguay             2790265.0    181034.0            18.9069
              Suriname             379918.0    163820.0             3.7727
              Peru               13562371.0   1285216.0            26.4933
              Paraguay            2408787.0    406752.0            16.6705
...                                     ...         ...                ...
Africa        Burkina Faso        5611666.0    272967.0            83.0641
              Botswana             592244.0    582000.0             4.5194
              Benin               3023443.0    112622.0           118.5635
              Angola              6029700.0   1246700.0            28.5466
              Algeria            13795915.0   2381741.0            18.8531

                            Growth Rate  World Population Percentage
Continent     Country
South America Venezuela          1.0036                         0.35
              Uruguay            0.9990                         0.04
              Suriname           1.0082                         0.01
              Peru               1.0099                         0.43
              Paraguay           1.0115                         0.09
...                                 ...                          ...
Africa        Burkina Faso       1.0259                         0.28
              Botswana           1.0162                         0.03
              Benin              1.0274                         0.17
              Angola             1.0315                         0.45
              Algeria            1.0164                         0.56

[234 rows x 16 columns]

In [69]:
df.sort_index(ascending =[False, True])

                              index  Rank CCA3       Capital  2022 Population  \
Continent     Country
South America Argentina           8    33  ARG  Buenos Aires       45510318.0
              Bolivia            24    80  BOL         Sucre       12224110.0
              Brazil             27     7  BRA      Brasilia      215313498.0
              Chile              40    65  CHL      Santiago       19603733.0
              Colombia           42    28  COL        Bogota       51874024.0
...                             ...   ...  ...           ...              ...
Africa        Tunisia           212    79  TUN         Tunis       12356117.0
              Uganda            217    31  UGA       Kampala       47249585.0
              Western Sahara    230   172  ESH      El Aaiún         575986.0
              Zambia            232    63  ZMB        Lusaka       20017675.0
              Zimbabwe          233    74  ZWE        Harare       16320537.0

                              2020 Population  2015 Population  \
Continent     Country
South America Argentina            45036032.0       43257065.0
              Bolivia              11936162.0       11090085.0
              Brazil              213196304.0      205188205.0
              Chile                19300315.0       17870124.0
              Colombia             50930662.0       47119728.0
...                                       ...              ...
Africa        Tunisia              12161723.0       11557779.0
              Uganda               44404611.0       37477356.0
              Western Sahara         556048.0         491824.0
              Zambia               18927715.0              NaN
              Zimbabwe             15669666.0       14154937.0

                              2010 Population  2000 Population  \
Continent     Country
South America Argentina            41100123.0       37070774.0
              Bolivia              10223270.0        8592656.0
              Brazil              196353492.0      175873720.0
              Chile                17004162.0       15351799.0
              Colombia                    NaN       39215135.0
...                                       ...              ...
Africa        Tunisia              10895063.0        9893316.0
              Uganda               32341728.0       24020697.0
              Western Sahara         413296.0         270375.0
              Zambia               13792086.0        9891136.0
              Zimbabwe             12839771.0       11834676.0

                              1990 Population  1980 Population  \
Continent     Country
South America Argentina            32637657.0       28024803.0
              Bolivia               7096194.0        5736088.0
              Brazil              150706446.0      122288383.0
              Chile                13342868.0       11469828.0
              Colombia             32601393.0       26176195.0
...                                       ...              ...
Africa        Tunisia               8440023.0        6578156.0
              Uganda               17586630.0       13284026.0
              Western Sahara         178529.0         116775.0
              Zambia                7686401.0        5720438.0
              Zimbabwe             10113893.0        7049926.0

                              1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
South America Argentina            23842803.0   2780400.0            16.3683
              Bolivia               4585693.0   1098581.0            11.1272
              Brazil               96369875.0   8515767.0            25.2841
              Chile                 9820481.0    756102.0            25.9274
              Colombia             20905254.0   1141748.0            45.4339
...                                       ...         ...                ...
Africa        Tunisia               5047404.0    163610.0            75.5218
              Uganda               10317212.0    241550.0           195.6100
              Western Sahara          76371.0    266000.0             2.1654
              Zambia                4281671.0    752612.0            26.5976
              Zimbabwe              5202918.0    390757.0            41.7665

                              Growth Rate  World Population Percentage
Continent     Country
South America Argentina            1.0052                         0.57
              Bolivia              1.0120                         0.15
              Brazil               1.0046                         2.70
              Chile                1.0057                         0.25
              Colombia             1.0069                         0.65
...                                   ...                          ...
Africa        Tunisia              1.0076                         0.15
              Uganda               1.0304                         0.59
              Western Sahara       1.0184                         0.01
              Zambia               1.0280                         0.25
              Zimbabwe             1.0204                         0.20

[234 rows x 16 columns]

In [73]:
df.loc['Angola'] # no funciona en este caso porque esta buscando con la primer columna

KeyError: 'Angola'

In [77]:
df.loc['Africa'] #Pone solo los paises de un solo continente, en este caso Africa

,index,Rank,CCA3,Capital,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Algeria,2,34,DZA,Algiers,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
Angola,5,42,AGO,Luanda,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
Benin,21,77,BEN,Porto-Novo,13352864.0,12643123.0,10932783.0,9445710.0,6998023.0,5133419.0,3833939.0,3023443.0,112622.0,118.5635,1.0274,0.17
Botswana,26,144,BWA,Gaborone,2630296.0,2546402.0,2305171.0,2091664.0,1726985.0,1341474.0,938578.0,592244.0,582000.0,4.5194,1.0162,0.03
Burkina Faso,31,58,BFA,Ouagadougou,22673762.0,21522626.0,18718019.0,16116845.0,11882888.0,9131361.0,6932967.0,5611666.0,272967.0,83.0641,1.0259,0.28
Burundi,32,78,BDI,Bujumbura,12889576.0,12220227.0,10727148.0,9126605.0,6307659.0,5483793.0,4312834.0,3497834.0,27834.0,463.0874,1.0270,0.16
Cameroon,34,53,CMR,Yaounde,27914536.0,26491087.0,23012646.0,19878036.0,15091594.0,11430520.0,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
Cape Verde,36,171,CPV,Praia,593149.0,582640.0,552166.0,521212.0,458251.0,364563.0,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
Central African Republic,38,117,CAF,Bangui,5579144.0,5343020.0,4819333.0,4660067.0,3759170.0,2809221.0,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
Chad,39,69,TCD,N'Djamena,17723315.0,16644701.0,14140274.0,11894727.0,8259137.0,5827069.0,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
Comoros,43,163,COM,Moroni,836774.0,806166.0,730216.0,656024.0,536758.0,431119.0,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
Djibouti,52,160,DJI,Djibouti,1120849.0,1090156.0,1006259.0,919199.0,742033.0,577173.0,324121.0,144379.0,23200.0,48.3125,1.0138,0.01
DR Congo,55,15,COD,Kinshasa,99010212.0,92853164.0,78656904.0,66391257.0,48616317.0,35987541.0,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
Egypt,57,14,EGY,Cairo,110990103.0,107465134.0,97723799.0,87252413.0,71371371.0,57214630.0,43748556.0,34781986.0,1002450.0,110.7188,1.0158,1.39
Equatorial Guinea,59,152,GNQ,Malabo,1674908.0,1596049.0,NaN,1094524.0,684977.0,465549.0,282509.0,316955.0,28051.0,59.7094,1.0247,0.02
Eritrea,60,132,ERI,Asmara,3684032.0,3555868.0,3340006.0,3147727.0,2392880.0,2149960.0,1657982.0,1272748.0,117600.0,31.3268,1.0176,0.05
Eswatini,62,159,SWZ,Mbabane,NaN,1180655.0,1133936.0,1099920.0,1030496.0,854011.0,598564.0,442865.0,17364.0,69.2047,1.0079,0.02
Ethiopia,63,12,ETH,Addis Ababa,123379924.0,117190911.0,102471895.0,89237791.0,67031867.0,47878073.0,34945469.0,28308246.0,1104300.0,111.7268,1.0257,1.55
Gabon,71,146,GAB,Libreville,2388992.0,2292573.0,2028517.0,1711105.0,1272935.0,983028.0,749078.0,597192.0,267668.0,8.9252,1.0204,0.03
Gambia,72,142,GMB,Banjul,2705992.0,2573995.0,2253133.0,NaN,NaN,NaN,NaN,NaN,10689.0,253.1567,1.0250,0.03
Ghana,75,47,GHA,Accra,33475870.0,32180401.0,28870939.0,25574719.0,19665502.0,15446982.0,11865246.0,8861895.0,238533.0,140.3406,1.0196,0.42
Guinea,84,75,GIN,Conakry,13859341.0,13205153.0,11625998.0,10270728.0,8336967.0,6354145.0,4972609.0,4222374.0,245857.0,56.3716,1.0242,0.17
Guinea-Bissau,85,149,GNB,Bissau,2105566.0,2015828.0,1788919.0,1567220.0,1230849.0,973551.0,831462.0,591663.0,36125.0,58.2856,1.0218,0.03
Ivory Coast,100,52,CIV,Yamoussoukro,28160542.0,26811790.0,23596741.0,21120042.0,16799670.0,11910540.0,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
Kenya,106,27,KEN,Nairobi,54027487.0,51985780.0,46851488.0,41517895.0,30851606.0,23162269.0,16187124.0,11473087.0,580367.0,93.0919,1.0193,0.68
Lesotho,113,147,LSO,Maseru,2305825.0,2254100.0,2118521.0,2022747.0,1998630.0,1798997.0,1407672.0,1023481.0,30355.0,75.9620,1.0107,0.03
Liberia,114,121,LBR,Monrovia,5302681.0,5087584.0,4612329.0,4019956.0,2895224.0,2209731.0,1932169.0,1463563.0,111369.0,47.6136,1.0210,0.07
Libya,115,107,LBY,Tripoli,6812341.0,6653942.0,6192235.0,6491988.0,5154790.0,4236983.0,2962720.0,1909177.0,1759540.0,3.8717,1.0114,0.09
Madagascar,120,50,MDG,Antananarivo,29611714.0,28225177.0,24850912.0,21731053.0,16216431.0,11882762.0,8948162.0,6639751.0,587041.0,50.4423,1.0241,0.37
Malawi,121,62,MWI,Lilongwe,20405317.0,19377061.0,16938942.0,14718422.0,11229387.0,9539665.0,6267369.0,4625141.0,118484.0,172.2200,1.0259,0.26
Mali,124,59,MLI,Bamako,22593590.0,21224040.0,18112907.0,15529181.0,11239101.0,8945026.0,7372581.0,6153587.0,1240192.0,18.2178,1.0314,0.28
Mauritania,128,126,MRT,Nouakchott,4736139.0,4498604.0,3946220.0,3419461.0,2695003.0,2006027.0,1506694.0,1122198.0,1030700.0,4.5951,1.0263,0.06
Mauritius,129,157,MUS,Port Louis,1299469.0,1297828.0,1293153.0,1283330.0,1215930.0,1090290.0,954865.0,830115.0,2040.0,636.9946,1.0004,0.02
Mayotte,130,182,MYT,Mamoudzou,326101.0,305587.0,249545.0,211786.0,159215.0,92659.0,52233.0,35383.0,374.0,871.9278,1.0319,0.00
Morocco,138,40,MAR,Rabat,37457971.0,36688772.0,34680458.0,32464865.0,28554415.0,24570814.0,19678444.0,15274351.0,446550.0,83.8830,1.0103,0.47
Mozambique,139,48,MOZ,Maputo,32969517.0,31178239.0,NaN,NaN,17768505.0,13303459.0,11413587.0,8411676.0,801590.0,41.1302,1.0278,0.41
Namibia,141,145,NAM,Windhoek,2567012.0,2489098.0,2282704.0,2099271.0,1819141.0,1369011.0,975994.0,754467.0,825615.0,3.1092,1.0146,0.03
Niger,148,54,NER,Niamey,26207977.0,24333639.0,20128124.0,16647543.0,11622665.0,8370647.0,6173177.0,4669708.0,1267000.0,20.6851,1.0378,0.33
Nigeria,149,6,NGA,Abuja,218541212.0,208327405.0,183995785.0,160952853.0,122851984.0,95214257.0,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
Republic of the Congo,168,114,COG,Brazzaville,5970424.0,5702174.0,5064386.0,4437884.0,3134030.0,2385435.0,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
Reunion,169,161,REU,Saint-Denis,974052.0,957822.0,922495.0,890130.0,785424.0,658992.0,551674.0,473925.0,2511.0,387.9140,1.0082,0.01
Rwanda,172,76,RWA,Kigali,13776698.0,13146362.0,11642959.0,10309031.0,8109989.0,7319962.0,5247532.0,3896367.0,26338.0,523.0731,1.0234,0.17
Sao Tome and Principe,181,187,STP,São Tomé,227380.0,218641.0,201124.0,182138.0,143714.0,120343.0,97210.0,77583.0,964.0,235.8714,1.0192,0.00
Senegal,183,72,SEN,Dakar,17316449.0,16436119.0,14356181.0,12530121.0,9704287.0,7536001.0,5703869.0,4367744.0,NaN,NaN,1.0261,0.22
Seychelles,185,196,SYC,Victoria,107118.0,105530.0,99240.0,92409.0,80060.0,71057.0,65290.0,54379.0,452.0,236.9867,1.0061,0.00
Sierra Leone,186,102,SLE,Freetown,8605718.0,8233969.0,7314773.0,6436698.0,4584067.0,4325388.0,3367477.0,2778557.0,71740.0,119.9570,1.0220,0.11
Somalia,192,70,SOM,Mogadishu,17597511.0,16537016.0,13763906.0,12026649.0,8721465.0,6999096.0,5892224.0,NaN,637657.0,27.5971,1.0312,0.22
South Africa,193,24,ZAF,Pretoria,59893885.0,58801927.0,55876504.0,51784921.0,46813266.0,39877570.0,29463549.0,22368306.0,1221037.0,49.0517,1.0084,0.75
South Sudan,195,86,SSD,Juba,10913164.0,10606227.0,11194299.0,NaN,6114440.0,4750817.0,4192011.0,3342410.0,619745.0,17.6091,1.0153,0.14
Sudan,198,32,SDN,Khartoum,46874204.0,44440486.0,38171178.0,33739933.0,26298773.0,21090886.0,16673586.0,11305206.0,1886068.0,24.8529,1.0267,0.59
Tanzania,205,22,TZA,Dodoma,65497748.0,61704518.0,52542823.0,45110527.0,34463704.0,26206012.0,19297659.0,13618192.0,945087.0,69.3034,1.0300,0.82
Togo,208,100,TGO,Lomé,8848699.0,8442580.0,7473229.0,6571855.0,5008035.0,3875947.0,2838110.0,2197383.0,56785.0,155.8281,1.0236,0.11
Tunisia,212,79,TUN,Tunis,12356117.0,12161723.0,11557779.0,10895063.0,9893316.0,8440023.0,6578156.0,5047404.0,163610.0,75.5218,1.0076,0.15
Uganda,217,31,UGA,Kampala,47249585.0,44404611.0,37477356.0,32341728.0,24020697.0,17586630.0,13284026.0,10317212.0,241550.0,195.6100,1.0304,0.59
Western Sahara,230,172,ESH,El Aaiún,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Zambia,232,63,ZMB,Lusaka,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,233,74,ZWE,Harare,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [79]:
df.loc['Africa', 'Angola'] # selecciona primero todos los paises del continene de Africa y luego solo se selecciona el pais - Angloa

index                                   5
Rank                                   42
CCA3                                  AGO
Capital                            Luanda
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: (Africa, Angola), dtype: object

In [85]:
df.iloc[1] # sigue poniendo Albania por que no ex multi indexing solo toma la parte inicial.

index                                  1
Rank                                 138
CCA3                                 ALB
Capital                           Tirana
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: (Europe, Albania), dtype: object